name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # Replace with your AWS region

      - name: Verify AWS CLI installation
        run: aws --version

      - name: Show current working directory and list repository contents
        run: |
          pwd
          ls -al
      
      - name: List S3 Buckets and Bucket Contents
        run: |
          echo "Listing S3 buckets..."
          aws s3 ls
          echo "Listing contents of S3 bucket static-content-ajay..."
          aws s3 ls s3://static-content-ajay --recursive

      - name: Deploy index.html to S3
        run: aws s3 cp index.html s3://static-content-ajay/index.html
      - name: Deploy Lambda function
        run: |
          aws lambda create-function \
            --function-name SubmitFormFunction \
            --runtime nodejs14.x \
            --role arn:aws:iam::891377087400:role/service-role/lambdafunction-role-vxa3dfwl:role/lambdafunction-rolevxa3dfwl \
            --handler submitFormLambda.handler \
            --zip-file fileb://submitFormLambda.zip
