name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # Replace with your AWS region

      - name: Verify AWS CLI installation
        run: aws --version

      - name: Validate AWS CLI configuration
        run: |
          echo "Validating AWS CLI configuration..."
          aws sts get-caller-identity

      - name: Show current working directory
        run: pwd

      - name: List repository contents
        run: ls -al

      - name: List S3 bucket contents
        run: aws s3 ls s3://static-content-ajay --recursive

      - name: Deploy index.html to S3
        run: aws s3 cp index.html s3://static-content-ajay/index.html --acl public-read
