name: Deploy to AWebS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # Replace with your AWS region

      - name: Verify AWS CLI installation
        run: aws --version

      - name: Validate AWS CLI configuration
        run: |
          echo "Validating AWS CLI configuration..."
          aws sts get-caller-identity

      - name: Show current working directory
        run: pwd

      - name: List repository contents
        run: ls -al

      - name: Check for index.html file
        run: |
          if [ ! -f "index.html" ]; then
            echo "index.html file does not exist in the root directory"
            exit 1
          else
            echo "index.html file exists"
          fi

      - name: Verify S3 bucket existence
        run: |
          echo "Checking S3 bucket existence..."
          if aws s3 ls "s3://static-content-ajay" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "S3 bucket does not exist"
            exit 1
          else
            echo "S3 bucket exists"
          fi

      - name: Deploy index.html to S3
        run: aws s3 cp index.html s3://static-content-ajay/index.html --acl public-read
